import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { booking, businessName, businessPhone, businessAddress } = await req.json();

    if (!booking) {
      return new Response(JSON.stringify({ error: "Booking data required" }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const invoiceNumber = `INV-${Date.now().toString(36).toUpperCase()}`;
    const date = new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' });

    // Generate HTML invoice
    const html = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; margin: 0; padding: 40px; color: #1a1a1a; }
    .invoice-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 40px; }
    .invoice-title { font-size: 32px; font-weight: 700; color: #6366f1; }
    .invoice-number { font-size: 14px; color: #666; margin-top: 4px; }
    .business-info { text-align: right; }
    .business-name { font-size: 18px; font-weight: 600; }
    .business-detail { font-size: 12px; color: #666; }
    .section { margin-bottom: 24px; }
    .section-title { font-size: 14px; font-weight: 600; color: #6366f1; margin-bottom: 8px; border-bottom: 2px solid #e5e7eb; padding-bottom: 4px; }
    .detail-row { display: flex; justify-content: space-between; padding: 6px 0; font-size: 13px; }
    .detail-label { color: #666; }
    .detail-value { font-weight: 500; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th { background: #f3f4f6; padding: 10px 12px; text-align: left; font-size: 12px; font-weight: 600; color: #374151; }
    td { padding: 10px 12px; border-bottom: 1px solid #e5e7eb; font-size: 13px; }
    .total-row { font-size: 16px; font-weight: 700; }
    .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #999; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; }
    .badge-confirmed { background: #fef3c7; color: #92400e; }
    .badge-completed { background: #d1fae5; color: #065f46; }
  </style>
</head>
<body>
  <div class="invoice-header">
    <div>
      <div class="invoice-title">INVOICE</div>
      <div class="invoice-number">${invoiceNumber}</div>
      <div class="invoice-number">Date: ${date}</div>
    </div>
    <div class="business-info">
      <div class="business-name">${businessName || booking.business_name}</div>
      ${businessPhone ? `<div class="business-detail">${businessPhone}</div>` : ''}
      ${businessAddress ? `<div class="business-detail">${businessAddress}</div>` : ''}
    </div>
  </div>

  <div class="section">
    <div class="section-title">Customer Details</div>
    <div class="detail-row"><span class="detail-label">Name</span><span class="detail-value">${booking.customer_name}</span></div>
    <div class="detail-row"><span class="detail-label">Phone</span><span class="detail-value">${booking.customer_phone}</span></div>
  </div>

  <div class="section">
    <div class="section-title">Booking Details</div>
    <div class="detail-row"><span class="detail-label">Booking ID</span><span class="detail-value">${booking.id?.slice(0, 8).toUpperCase() || 'N/A'}</span></div>
    <div class="detail-row"><span class="detail-label">Mode</span><span class="detail-value">${booking.mode === 'instant' ? '⚡ Instant' : '📅 Scheduled'}</span></div>
    ${booking.booking_date ? `<div class="detail-row"><span class="detail-label">Date</span><span class="detail-value">${booking.booking_date}</span></div>` : ''}
    ${booking.booking_time ? `<div class="detail-row"><span class="detail-label">Time</span><span class="detail-value">${booking.booking_time}</span></div>` : ''}
    <div class="detail-row"><span class="detail-label">Status</span><span class="detail-value"><span class="badge ${booking.status === 'completed' ? 'badge-completed' : 'badge-confirmed'}">${booking.status}</span></span></div>
    ${booking.notes ? `<div class="detail-row"><span class="detail-label">Notes</span><span class="detail-value">${booking.notes}</span></div>` : ''}
  </div>

  <div class="footer">
    <p>Thank you for your business!</p>
    <p>Generated by Instantly Platform • ${date}</p>
  </div>
</body>
</html>`;

    return new Response(JSON.stringify({ html, invoiceNumber }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
