/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#f7f7f7",
        foreground: "#1d212b",
        card: "#ffffff",
        "card-foreground": "#1d212b",
        popover: "#ffffff",
        "popover-foreground": "#1d212b",
        primary: "#2463eb",
        "primary-foreground": "#ffffff",
        secondary: "#f2f2f2",
        "secondary-foreground": "#1d212b",
        muted: "#f3f4f6",
        "muted-foreground": "#6a7181",
        accent: "#a8e619",
        "accent-foreground": "#1a1a1a",
        destructive: "#ef4343",
        "destructive-foreground": "#ffffff",
        success: "#28af60",
        "success-foreground": "#ffffff",
        warning: "#f59f0a",
        "warning-foreground": "#ffffff",
        border: "#e5e7eb",
        input: "#e5e7eb",
        ring: "#2463eb",
        sidebar: {
          DEFAULT: "#fafafa",
          foreground: "#3f3f46",
          primary: "#18181b",
          "primary-foreground": "#fafafa",
          accent: "#f4f4f5",
          "accent-foreground": "#18181b",
          border: "#e5e7eb",
          ring: "#2463eb",
        },
      },
      borderRadius: {
        lg: "12px",
        md: "10px",
        sm: "8px",
      },
      fontFamily: {
        sans: ["PlusJakartaSans_400Regular"],
        "sans-medium": ["PlusJakartaSans_500Medium"],
        "sans-semibold": ["PlusJakartaSans_600SemiBold"],
        "sans-bold": ["PlusJakartaSans_700Bold"],
        "sans-extrabold": ["PlusJakartaSans_800ExtraBold"],
      },
    },
  },
  plugins: [],
};
