export type RootStackParamList = {
  Home: undefined;
  MyCards: undefined;
  CardCreate: { cardId?: string; plan?: string; skipPreview?: boolean } | undefined;
  BusinessPromotionForm: { plan?: string } | undefined;
  PremiumPlanSelection: { formData?: any } | undefined;
  FreePlanConfirmation: undefined;
  BusinessDetail: { id: string } | undefined;
  CategoryDetail: { id: string } | undefined;
  SubcategoryDetail: { subcategory: string; categoryName: string; categoryIcon: string } | undefined;
  Messaging: { initialTab?: string } | undefined;
  Vouchers: undefined;
  VoucherDetail: { id: string } | undefined;
  MyVouchers: undefined;
  Ads: undefined;
  AdCreate: { cardId?: string } | undefined;
  AdDashboard: undefined;
  Events: undefined;
  EventDetail: { id: string } | undefined;
  EventScanner: undefined;
  CardScanner: undefined;
  UnifiedScanner: undefined;
  EventCreate: undefined;
  VoucherCreate: { promotionId?: number } | undefined;
  PublicCard: { id: string } | undefined;
  MyPasses: undefined;
  Profile: undefined;
  ChooseListingType: undefined;
  Dashboard: undefined;
  BusinessAnalytics: undefined;
  Subscription: undefined;
  Notifications: undefined;
  BusinessDashboard: undefined;
  BusinessSelectorScreen: undefined;
  AdminDashboard: { tab?: string } | undefined;
  AdminAdDetail: { id: number } | undefined;
  EditProfile: undefined;
  PaymentMethods: undefined;
  PrivacySecurity: undefined;
  ReferAndEarn: undefined;
  ReferralHistory: undefined;
  EarningsHistory: undefined;
  PerReferralInfo: undefined;
  MyFavourites: undefined;
  TrackBooking: undefined;
  BookingDetail: { id: string | number } | undefined;
  EventEdit: { id: string | number } | undefined;
  EventAgendaEdit: { id: string | number };
  EventRegistrations: { id: string | number } | undefined;
  EventAnalytics: { id: string | number } | undefined;
  MyEvents: undefined;
  PassDetail: { passId: string | number } | undefined;
  QRView: { passId: string | number };
  Support: undefined;
  NearbyBusinesses: undefined;
  LoyaltyPoints: undefined;
  Credits: undefined;
  TransferCredits: undefined;
  SendCredits: { recipient: { _id: number | string; name: string | null; phone: string; profilePic: string | null } } | undefined;
  CreditsHistory: undefined;
  Auth: { redirect?: string; redirectParams?: any } | undefined;
  ForgotPasswordPhone: undefined;
  ForgotPasswordOTP: { phone: string } | undefined;
  ForgotPasswordReset: { phone: string; otp: string } | undefined;
  GroupChat: { groupId: number; groupName: string };
  GroupJoin: { code: string };
  NotFound: undefined;
};
