export type RootStackParamList = {
  Home: undefined;
  MyCards: undefined;
  CardCreate: { cardId?: string; plan?: string } | undefined;
  BusinessDetail: { id: string } | undefined;
  CategoryDetail: { id: string } | undefined;
  SubcategoryDetail: { subcategory: string; categoryName: string; categoryIcon: string } | undefined;
  Messaging: undefined;
  Vouchers: undefined;
  VoucherDetail: { id: string } | undefined;
  MyVouchers: undefined;
  Ads: undefined;
  AdCreate: { cardId?: string } | undefined;
  AdDashboard: undefined;
  Events: undefined;
  EventDetail: { id: string } | undefined;
  EventScanner: undefined;
  EventCreate: undefined;
  VoucherCreate: undefined;
  PublicCard: { id: string } | undefined;
  MyPasses: undefined;
  Profile: undefined;
  ChooseListingType: undefined;
  Dashboard: undefined;
  BusinessAnalytics: undefined;
  Subscription: undefined;
  Notifications: undefined;
  BusinessDashboard: undefined;
  AdminDashboard: { tab?: string } | undefined;
  EditProfile: undefined;
  PaymentMethods: undefined;
  PrivacySecurity: undefined;
  ReferAndEarn: undefined;
  MyFavourites: undefined;
  TrackBooking: undefined;
  BookingDetail: { id: string | number } | undefined;
  EventEdit: { id: string | number } | undefined;
  EventRegistrations: { id: string | number } | undefined;
  PassDetail: { passId: string | number } | undefined;
  Support: undefined;
  NearbyBusinesses: undefined;
  LoyaltyPoints: undefined;
  Auth: undefined;
  NotFound: undefined;
};
