export const colors = {
  background: "#f7f7f7",
  foreground: "#1d212b",
  card: "#ffffff",
  cardForeground: "#1d212b",
  popover: "#ffffff",
  popoverForeground: "#1d212b",
  primary: "#2463eb",
  primaryForeground: "#ffffff",
  secondary: "#f2f2f2",
  secondaryForeground: "#1d212b",
  muted: "#f3f4f6",
  mutedForeground: "#6a7181",
  accent: "#a8e619",
  accentForeground: "#1a1a1a",
  destructive: "#ef4343",
  destructiveForeground: "#ffffff",
  success: "#28af60",
  successForeground: "#ffffff",
  warning: "#f59f0a",
  warningForeground: "#ffffff",
  border: "#e5e7eb",
  input: "#e5e7eb",
  ring: "#2463eb",
  sidebar: {
    background: "#fafafa",
    foreground: "#3f3f46",
    primary: "#18181b",
    primaryForeground: "#fafafa",
    accent: "#f4f4f5",
    accentForeground: "#18181b",
    border: "#e5e7eb",
    ring: "#2463eb",
  },
};
